apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: labs
  namespace: flux-system
spec:
  interval: 1m
  path: ./labs
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeskills-grow
