apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  containers:
    - name: secure-container
      image: busybox
      command: ["sleep", "3600"]
