apiVersion: v1
kind: Pod
metadata:
  name: nginx-sooka
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged:stable
      ports:
        - containerPort: 80
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
